theme: ./theme

siteConfig:
  title: Ex Post Ante
  url: https://example.com
  author: Elias Little
  email: eliasjlittle+xpa@gmail.com
  description: Write an awesome description for your new site here. You can edit this line in saber-config.yml. It will appear in your document head meta (for Google search results) site description.

themeConfig:
  nav:
    - text: Home
      link: /
    - text: About
      link: /about 
    - text: Contact
      link: /contact
  social:
    twitter: EliasJLittle
    github: EliasLittle
    rss: false

plugins:
  - resolve: saber-plugin-query-posts
  - resolve: saber-plugin-feed
    options:
      atomFeed: true
  - resolve: saber-plugin-prismjs
  - resolve: saber-plugin-search
